version: '3'
name: nest-ms-dev

services:
  nats-server:
    image: nats:2.10-alpine3.20
    ports:
      - "8222:8222"
      - "4222:4222"

  client-gateway:
    build: ./client-gateway
    image: client-gateway-dev
    ports:
      # SERVER:DOCKER
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
    depends_on:
      - nats-server

  products-ms:
    build: ./products-ms
    image: products-ms-dev
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run compose:start
    environment:
      - PORT=3001
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db
    depends_on:
      - nats-server

  orders-ms:
    build: ./orders-ms
    image: orders-ms-dev
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run compose:start
    environment:
      - PORT=3002
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/orders-db?schema=public
    depends_on:
      - nats-server
      - orders-db

  orders-db:
    container_name: orders_db
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=orders-db

  payments-ms:
    build: ./payments-ms
    image: payments-ms-dev
    ports:
      # SERVER:DOCKER
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
    depends_on:
      - nats-server

  auth-ms:
    build: ./auth-ms
    image: auth-ms-dev
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run compose:start
    environment:
      - PORT=3004
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${MONGO_DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_EXPIRATION=3d
    depends_on:
      - nats-server