version: '3'
name: nest-ms-prod

services:
  nats-server:
    image: nats:2.10-alpine3.20
    ports:
      - "8222:8222"

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
    depends_on:
      - nats-server

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: products-ms-prod
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db
    depends_on:
      - client-gateway

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DB_URL=${ORDERS_DB_URL}
    image: orders-ms-prod
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${ORDERS_DB_URL}
    depends_on:
      - products-ms

  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: payments-ms-prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
    depends_on:
      - orders-ms

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-ms-prod
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${MONGO_DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_EXPIRATION=3h
    depends_on:
      - payments-ms